# Generated by Django 5.0.2 on 2024-03-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
