# Generated by Django 5.0.2 on 2024-03-28 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('semester_cleared', models.CharField(max_length=20)),
                ('extracurricular', models.CharField(max_length=200)),
                ('cocurricular', models.CharField(max_length=200)),
                ('attendance_percentage', models.FloatField()),
                ('cgpi', models.FloatField()),
                ('sgpi', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
